
from __future__ import annotations

from typing import Literal, Optional

from pydantic import AliasChoices, BaseModel, ConfigDict, Field, model_validator

class WorldObject(BaseModel):
    """Canonical world object used by the new workflow."""

    id: str = Field(description="Stable short snake_case object identifier")
    name: str = Field(description="Display name")
    appearance: str = Field(description="Canonical appearance description")
    constraints: list[str] = Field(default_factory=list, description="Must-preserve constraints")
    story_role: Literal["character", "environment", "prop", "threat", "creature", "vehicle", "object"] = Field(
        default="object",
        description="Narrative role of the object inside the scene",
    )
    default_visibility: Literal["always_visible", "latent", "reveal_only", "conditional"] = Field(
        default="always_visible",
        description="Default visibility policy across the scene timeline",
    )
    reveal_rules: list[str] = Field(default_factory=list, description="Conditions that allow a full reveal")
    pre_reveal_hints: list[str] = Field(default_factory=list, description="Allowed pre-reveal hint phrases")
    hard_exclusions_before_reveal: list[str] = Field(
        default_factory=list,
        description="Explicit exclusions before the object is allowed to be revealed",
    )
class StoryStyleGuide(BaseModel):
    """Canonical style guide used by the new workflow."""

    style: str = Field(description="Visual style")
    palette: str = Field(description="Palette description")
    cinematic_intent: str = Field(default="", description="High-level cinematic intent for the scene")
    camera_language: str = Field(default="", description="Global camera-language guidance")
    lighting_logic: str = Field(default="", description="Global lighting logic shared across shots")
    continuity_bible: list[str] = Field(default_factory=list, description="Short reusable continuity lock phrases")
    global_continuity_locks: list[str] = Field(default_factory=list, description="Scene-wide continuity locks")
    public_continuity_locks: list[str] = Field(default_factory=list, description="Pre-reveal-safe continuity locks")
    reveal_locked_traits: list[str] = Field(default_factory=list, description="Locked traits used only after reveal")
    global_negative: list[str] = Field(default_factory=list, description="Scene-wide negative prompts")
class WorldDescription(BaseModel):
    """Canonical world package generated by the director."""

    scene_background: str = Field(description="Scene background/environment")
    objects: list[WorldObject] = Field(default_factory=list, description="Objects or characters in scene")
    primary_subject_ids: list[str] = Field(default_factory=list, description="Main hero or subject ids that must stay tracked across anchor frames")
    style_guide: StoryStyleGuide = Field(description="Global scene style guide")
class StoryBeatData(BaseModel):
    """Narrative beat used to decouple story progression from a fixed frame count."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    idx: int = Field(
        ge=0,
        validation_alias=AliasChoices("idx", "index"),
        serialization_alias="idx",
        description="0-based beat index",
    )
    id: str = Field(description="Stable beat identifier")
    label: str = Field(default="", description="Short human-readable beat label")
    narrative_function: str = Field(default="", description="Narrative function such as reveal or reaction")
    goal: str = Field(default="", description="What the beat must achieve on screen")
    emotion: str = Field(default="", description="Primary emotional state of the beat")
    visible_objects: list[str] = Field(default_factory=list, description="Object ids allowed to be fully visible")
    latent_objects: list[str] = Field(default_factory=list, description="Object ids that must stay hidden")
    allowed_hints: list[str] = Field(default_factory=list, description="Allowed indirect hints for latent objects")
    motion_intensity: str = Field(default="", description="Low/medium/high motion intensity guidance")
class StoryboardFrameData(BaseModel):
    """Canonical storyboard frame used across tasks and artifacts."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    idx: int = Field(
        ge=0,
        validation_alias=AliasChoices("idx", "index"),
        serialization_alias="idx",
        description="0-based frame index",
    )
    action_in_frame: str = Field(default="", description="What happens in this frame")
    camera: str = Field(default="", description="Camera framing or movement for the frame")
    lighting: str = Field(default="", description="Lighting instructions")
    shot_size: str = Field(default="", description="Shot size, e.g. wide shot or medium close-up")
    camera_angle: str = Field(default="", description="Camera angle, e.g. eye level or low angle")
    lens: str = Field(default="", description="Lens or focal length language for the shot")
    camera_support: str = Field(default="", description="Camera support, e.g. tripod, handheld, dolly")
    composition: str = Field(default="", description="Composition notes for the frame")
    blocking: str = Field(default="", description="Subject and object placement / staging")
    screen_position: str = Field(default="", description="Where the dominant subject sits on screen")
    body_facing: str = Field(default="", description="Body orientation of the dominant subject")
    travel_direction: str = Field(default="", description="Screen-space direction of movement")
    gaze_direction: str = Field(default="", description="Screen-space direction of eyeline")
    gaze_target: str = Field(default="", description="Object or point that receives the gaze")
    camera_axis_side: str = Field(default="", description="Named side of the camera axis / line of action")
    emotional_beat: str = Field(default="", description="Emotional beat captured in the frame")
    beat_id: str = Field(default="", description="Beat identifier this frame belongs to")
    frame_class: str = Field(default="", description="Frame class such as establishing, reaction, or reveal")
    continuity_anchors: list[str] = Field(default_factory=list, description="Frame-level continuity lock phrases")
    visible_object_ids: list[str] = Field(default_factory=list, description="Object ids allowed to be fully visible")
    hidden_object_ids: list[str] = Field(default_factory=list, description="Object ids that must stay hidden")
    hint_object_ids: list[str] = Field(default_factory=list, description="Object ids allowed only as indirect hints")
    hero_presence: dict[str, str] = Field(default_factory=dict, description="Per-primary-subject presence state in the frame")
    hero_scale: dict[str, str] = Field(default_factory=dict, description="Per-primary-subject scale or prominence state in the frame")
    must_have: list[str] = Field(default_factory=list, description="Elements that must appear")
    negative: list[str] = Field(default_factory=list, description="Frame-specific negative prompts")
    image_prompt: str = Field(
        default="",
        validation_alias=AliasChoices("image_prompt", "prompt"),
        serialization_alias="image_prompt",
        description="Image generation prompt",
    )
    keyframe_uri: Optional[str] = Field(default=None, description="Stored keyframe URI")
    fix_description: str = Field(default="", description="Optional hint captured during fixes")
class StoryboardSegmentData(BaseModel):
    """Canonical storyboard segment used across tasks and artifacts."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    idx: int = Field(
        ge=0,
        validation_alias=AliasChoices("idx", "index"),
        serialization_alias="idx",
        description="0-based segment index",
    )
    start_frame_idx: int = Field(ge=0, description="Start frame index")
    end_frame_idx: int = Field(ge=0, description="End frame index")
    duration: float = Field(
        ge=3.0,
        le=15.0,
        validation_alias=AliasChoices("duration", "duration_sec"),
        serialization_alias="duration",
        description="Segment duration in seconds",
    )
    transition_text: str = Field(default="", description="Narrative description of the transition")
    camera_move: str = Field(default="", description="Primary camera move for the segment")
    subject_motion: str = Field(default="", description="Primary subject motion across the segment")
    environment_motion: str = Field(default="", description="Environmental motion across the segment")
    screen_direction_rule: str = Field(default="", description="Rule for preserving or intentionally changing screen direction")
    gaze_continuity_rule: str = Field(default="", description="Rule for preserving eyeline continuity")
    camera_axis_rule: str = Field(default="", description="Rule for preserving or intentionally breaking the axis")
    motion_beats: list[str] = Field(default_factory=list, description="Ordered motion beats for the segment")
    beat_id: str = Field(default="", description="Beat identifier this segment resolves into")
    segment_class: str = Field(default="", description="Segment class such as reveal_bridge or escalation_bridge")
    continuity_anchors: list[str] = Field(default_factory=list, description="Segment-level continuity locks")
    visible_object_ids: list[str] = Field(default_factory=list, description="Object ids allowed to be fully visible")
    hidden_object_ids: list[str] = Field(default_factory=list, description="Object ids that must stay hidden")
    hint_object_ids: list[str] = Field(default_factory=list, description="Object ids allowed only as indirect hints")
    visibility_transition: dict[str, list[str]] = Field(
        default_factory=dict,
        description="Transition details for persistent, revealed, hidden, and hinted objects",
    )
    hero_presence_transition: dict[str, str] = Field(default_factory=dict, description="Per-primary-subject continuity state across the segment")
    entry_exit_actions: list[str] = Field(default_factory=list, description="Explicit exit/entry actions for primary subjects")
    offscreen_justification: str = Field(default="", description="Why a primary subject is allowed to leave the frame")
    end_match_notes: str = Field(default="", description="Explicit instructions for how the clip must land on the next keyframe")
    video_prompt: str = Field(
        default="",
        validation_alias=AliasChoices("video_prompt", "kling_prompt"),
        serialization_alias="video_prompt",
        description="Prompt for image-to-video generation",
    )
    negative: list[str] = Field(default_factory=list, description="Segment-specific negative prompts")
    result_uri: Optional[str] = Field(default=None, description="Stored video segment URI")

    @property
    def kling_prompt(self) -> str:
        """Backward-compatible alias for persisted storyboards."""
        return self.video_prompt

    @kling_prompt.setter
    def kling_prompt(self, value: str) -> None:
        self.video_prompt = value
class StoryboardData(BaseModel):
    """Canonical storyboard package generated by the director."""

    scene_background: str = Field(description="Scene background/environment")
    objects: list[WorldObject] = Field(default_factory=list, description="Objects or characters in scene")
    primary_subject_ids: list[str] = Field(default_factory=list, description="Main hero or subject ids that must stay tracked across anchor frames")
    style_guide: StoryStyleGuide = Field(description="Global scene style guide")
    story_beats: list[StoryBeatData] = Field(default_factory=list)
    frames: list[StoryboardFrameData] = Field(default_factory=list)
    segments: list[StoryboardSegmentData] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_storyboard(self) -> "StoryboardData":
        """Validate frame and segment topology."""
        if not self.frames:
            raise ValueError("Storyboard must have at least one frame")

        expected_segments = max(0, len(self.frames) - 1)
        if len(self.segments) != expected_segments:
            raise ValueError(
                f"Storyboard must have N-1 segments: {len(self.frames)} frames require "
                f"{expected_segments} segments, got {len(self.segments)}"
            )

        for expected_idx, frame in enumerate(self.frames):
            if frame.idx != expected_idx:
                raise ValueError(f"Frame {expected_idx} idx must be {expected_idx}, got {frame.idx}")

        for expected_idx, beat in enumerate(self.story_beats):
            if beat.idx != expected_idx:
                raise ValueError(f"Beat {expected_idx} idx must be {expected_idx}, got {beat.idx}")

        for expected_idx, segment in enumerate(self.segments):
            if segment.idx != expected_idx:
                raise ValueError(f"Segment {expected_idx} idx must be {expected_idx}, got {segment.idx}")
            if segment.start_frame_idx != expected_idx:
                raise ValueError(
                    f"Segment {expected_idx} start_frame_idx must be {expected_idx}, got {segment.start_frame_idx}"
                )
            if segment.end_frame_idx != expected_idx + 1:
                raise ValueError(
                    f"Segment {expected_idx} end_frame_idx must be {expected_idx + 1}, got {segment.end_frame_idx}"
                )

        return self

    def total_duration(self) -> float:
        """Calculate total duration from segment durations."""
        return sum(segment.duration for segment in self.segments)
